apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: py-k8s-app-envs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: staging
          - env: qa
          - env: prod
  template:
    metadata:
      name: 'py-{{env}}-app'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Shrikant155/k8s-test-app.git
        targetRevision: main
        path: mychart
        helm:
          valueFiles:
            - 'values-{{env}}.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
